### ISSUE TITLE
Test active coordinates 

### ISSUE THREAD

**Issue by yachmena** [CFEL-CMI/roaming_cf2i2#1]
Hi @nidin1996,

when I run 1D scans of each of active coordinates $r$, $\theta$, or $\phi$
```
def test_coords(atomLabels):
    # equilibrium
    coo0 = init_coord()
    r0 = 1.44
    theta0 = 0
    phi0 = 0
    writeXYZ('test_coords.xyz', atomLabels, coo0)

    # scan r
    r = np.linspace(r0, 10, 100)
    theta = [theta0]*len(r)
    phi = [phi0]*len(r)
    for x in zip(r, theta, phi):
        coo = change_coord(coo0, *x)
        writeXYZ('test_coords.xyz', atomLabels, coo, append=True)

    # scan theta
    theta = np.linspace(0, np.pi, 100)
    r = [r0]*len(theta)
    phi = [phi0]*len(theta)
    for x in zip(r, theta, phi):
        coo = change_coord(coo0, *x)
        writeXYZ('test_coords.xyz', atomLabels, coo, append=True)

    # scan phi
    phi = np.linspace(0, 2*np.pi, 100)
    r = [r0]*len(phi)
    theta = [theta0]*len(phi)
    for x in zip(r, theta, phi):
        coo = change_coord(coo0, *x)
        writeXYZ('test_coords.xyz', atomLabels, coo, append=True)
```

It produces the following XYZ output: [https://github.com/CFEL-CMI/roaming_cf2i2/blob/develop/scripts/test_coords.xyz](https://github.com/CFEL-CMI/roaming_cf2i2/blob/develop/scripts/test_coords.xyz)
... or visualized with Avogadro: [https://github.com/CFEL-CMI/roaming_cf2i2/blob/develop/scripts/test_coords.mov](https://github.com/CFEL-CMI/roaming_cf2i2/blob/develop/scripts/test_coords.mov)

I am curious if this behaviour is correct (I think it is not)

**Comment by nidin1996** [comment]
I have made changes in the change_coord file. there is a movie if you like to see it. (https://github.com/CFEL-CMI/roaming_cf2i2/blob/develop/scripts/test.mov)
The problem was that I was converting radian to radian again.
I was thinking of rotating fragments also.

**Comment by nidin1996** [comment]
Hi @yachmena ,
Could you look into the changes I have made? I hope they are fine now.
I have added another function where you can rotate the fragment (CF2I). I am not sure how useful it would be.
https://github.com/CFEL-CMI/roaming_cf2i2/blob/develop/scripts/coordinates.py
